name: Vality basic linters

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2
      - name: 🚀 Run yamllint
        uses: frenck/action-yamllint@v1
        with:
          warnings: false
