name: Vality basic linters

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2

      - name: 🚀 Run yamllint
        uses: reviewdog/action-yamllint@v1
        with:
          filter_mode: nofilter
          yamllint_flags: >-
            . --no-warnings -d "{extends: default, rules: {line-length: {max:
            120}}}"
