name: Vality workflows sync

on:
  push:
    branches:
      - master
      - main

env:
  REPO_LIMIT: 1000

jobs:
  workflows-sync:
    name: Sync files in ${{ matrix.language }} repositories
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - language: thrift
            file_patterns: |
              ^LICENSE$
            workflow_patterns: |
              ^basic-linters\.yml$
          - language: erlang
            file_patterns: |
              ^LICENSE$
            workflow_patterns: |
              ^basic-linters\.yml$
          - language: java
            file_patterns: |
              ^LICENSE$
            workflow_patterns: |
              ^basic-linters\.yml$
    steps:
      - name: 📤 Get a list of ${{ matrix.language }} repositories
        run: |
          REPOSITORIES=$(gh repo list \
              $OWNER \
              --source \
              --no-archived \
              -L $REPO_LIMIT \
              - l ${{ matrix.language }} \
              --json name,owner \
          -q '.[] | [.owner.login, .name] | join("/")')
          echo "REPOSITORIES<<EOF" >> $GITHUB_ENV
          echo "$REPOSITORIES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
      - name: 🔄 Sync main files
        uses: adrianjost/files-sync-action@v1.5.0
        with:
          TARGET_REPOS: ${{ env.REPOSITORIES }}
          FILE_PATTERNS: ${{ matrix.file_patterns }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      - name: 🔄 Sync workflow files
        uses: adrianjost/files-sync-action@v1.5.0
        with:
          TARGET_REPOS: ${{ env.REPOSITORIES }}
          FILE_PATTERNS: ${{ matrix.workflow_patterns }}
          SRC_ROOT: "/workflow-templates/"
          TARGET_ROOT: "/.github/workflows/"
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
